package generator.registry.command;

import java.awt.Component;

import generator.interfaces.ITranslate;
import generator.main.GenerationException;

/** Represents a part of a Structure. */
public abstract class Argument implements ITranslate
{

	/** @return The Component used to let the user determine how this Argument is used. */
	public abstract Component getComponent();

	/** @return True if this Argument is currently being used for the Command generation. */
	public boolean isUsed()
	{
		// TODO Argument.isUsed()
		return false;
	}

	/** @return The part of the Command generated by this Argument.
	 * @throws GenerationException If the user input wrong data. */
	public abstract String generate() throws GenerationException;

}
